## Numpy

### np.array()

In [3]:
import numpy as np

In [4]:
l = [1,2,3,4,5,6]
l

[1, 2, 3, 4, 5, 6]

In [5]:
npa = np.array(l)

In [6]:
npa

array([1, 2, 3, 4, 5, 6])

In [7]:
type(l), type(npa)

(list, numpy.ndarray)

In [8]:
l.append('string')
npa = np.array(l)
npa

array(['1', '2', '3', '4', '5', '6', 'string'], dtype='<U11')

In [10]:
l1=[1,2,3,4,5,6]
l2 = [1,2,3,4,5,6]

In [11]:
l1+l2

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [12]:
np.array(l1+l2)

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [13]:
l+20

TypeError: can only concatenate list (not "int") to list

In [15]:
l1 + [20]


[1, 2, 3, 4, 5, 6, 20]

In [16]:
l = [[1,2],[3,4],[5,6]]

In [18]:
npa2d = np.array(l)
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
npa2d.shape

(3, 2)

In [20]:
npa2d = np.array(l, dtype = 'float')
npa2d

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [21]:
npa2d.astype('int')

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
npa2d = npa2d.astype('str')

In [28]:
npa2d

array([['1.0', '2.0'],
       ['3.0', '4.0'],
       ['5.0', '6.0']], dtype='<U32')

In [29]:
npa2d[0][0] +1

TypeError: can only concatenate str (not "int") to str

In [31]:
npa2d[0][0] +str(1)

'1.01'

### np.nan and np.inf

In [34]:
np.nan == np.nan

False

In [36]:
None == None

True

In [37]:
np.inf == np.inf

True

In [39]:
npa2d = npa2d.astype('int')

ValueError: invalid literal for int() with base 10: '1.0'

In [40]:
npa2d = npa2d.astype('float')

In [41]:
npa2d


array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [42]:
npa2d = npa2d.astype('int')

In [43]:
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
npa2d[0][0] = np.nan
npa2d[1][1] =np.inf 

ValueError: cannot convert float NaN to integer

In [45]:
npa2d = npa2d.astype('float')

In [46]:
npa2d[0][0] = np.nan
npa2d[1][1] =np.inf 

In [47]:
npa2d

array([[nan,  2.],
       [ 3., inf],
       [ 5.,  6.]])

In [49]:
np.isnan(npa2d)

array([[ True, False],
       [False, False],
       [False, False]])

In [50]:
np.isinf(npa2d)

array([[False, False],
       [False,  True],
       [False, False]])

In [51]:
npa2d

array([[nan,  2.],
       [ 3., inf],
       [ 5.,  6.]])

In [52]:
flag = np.isnan(npa2d)| np.isinf(npa2d)
flag

array([[ True, False],
       [False,  True],
       [False, False]])

In [54]:
npa2d[flag]

array([nan, inf])

In [55]:
npa2d[flag] = 0

In [56]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

### Statistical OPeartion 

In [57]:
# mean , varience , std, median 

In [58]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [59]:
npa2d.mean()

2.6666666666666665

In [61]:
npa2d.min()

0.0

In [62]:
npa2d.max()

6.0

In [63]:
npa2d.var()

5.222222222222222

In [64]:
npa2d.std()

2.2852182001336816

In [65]:
npa2d.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [66]:
np.median(npa2d)

2.5

### Shape(), Reshape(), Ravwl()

In [67]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [68]:
npa2d.shape

(3, 2)

In [69]:
npa2d.reshape(2,3)

array([[0., 2., 3.],
       [0., 5., 6.]])

In [70]:
npa2d.reshape(1,3) #size metter

ValueError: cannot reshape array of size 6 into shape (1,3)

In [71]:
npa2d.reshape(1,6)

array([[0., 2., 3., 0., 5., 6.]])

In [72]:
npa2d.reshape(6,1)

array([[0.],
       [2.],
       [3.],
       [0.],
       [5.],
       [6.]])

####  ravel is used for concert 2d into 1d 

In [73]:
npa2d.reshape(1,6).ravel()

array([0., 2., 3., 0., 5., 6.])

In [75]:
npa2d.flatten()

array([0., 2., 3., 0., 5., 6.])

In [77]:
np.reshape(npa2d, (1,6))

array([[0., 2., 3., 0., 5., 6.]])

### Sequence, repetitions, and random numbers



#### arange(), Linspace(),and random numbers

In [78]:
np.arange(1,5)

array([1, 2, 3, 4])

In [79]:
np.arange(1,5, dtype = 'float')

array([1., 2., 3., 4.])

In [80]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [81]:
np.linspace(1,20,3)

array([ 1. , 10.5, 20. ])

In [82]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [83]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [84]:
np.zeros([1,5])

array([[0., 0., 0., 0., 0.]])

In [85]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [86]:
np.zeros([2,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [87]:
np.ones([1,2])

array([[1., 1.]])

In [88]:
np.ones([1,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [89]:
np.tile([1,2],3)  # repaeted in particualr sequence, repeat whole list 

array([1, 2, 1, 2, 1, 2])

In [90]:
np.repeat([1,2],3) #repaet fisrt element then repeat sevcond element

array([1, 1, 1, 2, 2, 2])

In [92]:
np.random.rand(3,3)  #3x3 matrix

array([[0.72582485, 0.08807973, 0.9039366 ],
       [0.94683023, 0.7463346 , 0.17252231],
       [0.78459002, 0.38788513, 0.65945476]])

In [94]:
np.random.randint(0,10, [3,3])  # number , [size]

array([[0, 9, 3],
       [1, 4, 8],
       [6, 2, 9]])

In [99]:
np.random.randint(0,100, [3,3])  # number , [size]

array([[76, 17, 24],
       [74, 49, 95],
       [54, 33, 23]])

In [100]:
np.random.seed(1)  #fixe the random number 

In [102]:
np.random.randint(0,100, [3,3])  # number , [size]

array([[ 1, 76, 71],
       [ 6, 25, 50],
       [20, 18, 84]])

In [108]:
np.random.seed(1)
np.random.randint(0,100, [3,3])  # number , [size]

array([[37, 12, 72],
       [ 9, 75,  5],
       [79, 64, 16]])

In [110]:
np.unique(npa2d)

array([0., 2., 3., 5., 6.])

In [111]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [112]:
np.unique(npa2d, return_counts=True)  # how many time numer occuring 

(array([0., 2., 3., 5., 6.]), array([2, 1, 1, 1, 1], dtype=int64))

## Where()

In [114]:
arr = np.array([3,5,67,45,4,6,4])

In [115]:
arr

array([ 3,  5, 67, 45,  4,  6,  4])

In [116]:
np.where(arr>10)

(array([2, 3], dtype=int64),)

In [119]:
index = np.where(arr>10)
arr[index]

array([67, 45])

In [120]:
index = np.where(arr<10)
arr[index]

array([3, 5, 4, 6, 4])

In [121]:
index = np.where(arr==10)
arr[index]

array([], dtype=int32)

In [122]:
index = np.where(arr==5)
arr[index]

array([5])

In [123]:
arr>10

array([False, False,  True,  True, False, False, False])

In [124]:
arr[arr>10]

array([67, 45])

In [125]:
arr.max()

67

In [126]:
# index of max 
arr.argmax()

2

In [128]:
arr.argmin()

0

In [130]:
arr[arr.argmax()]

67

## File Read and write 

In [131]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [133]:
np.savetxt('npa2d.csv', npa2d, delimiter=',')

In [134]:
np.loadtxt('npa2d.csv', delimiter=',')

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [136]:
# byte fomate
np.save('daya.npy', npa2d)

In [137]:
np.load('daya.npy')

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [138]:
arr

array([ 3,  5, 67, 45,  4,  6,  4])

In [140]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [141]:
np.savez('both.npz', arr, npa2d)

In [142]:
np.load('both.npz')

In [143]:
np.load('both.npz').files

['arr_0', 'arr_1']

In [144]:
d = np.load('both.npz')
d.files

['arr_0', 'arr_1']

In [147]:
d[d.files[0]]

array([ 3,  5, 67, 45,  4,  6,  4])

In [148]:
d[d.files[1]]

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

##  Concetinate and Sorting

In [149]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [150]:
np.concatenate([npa2d, npa2d], axis = 0)

array([[0., 2.],
       [3., 0.],
       [5., 6.],
       [0., 2.],
       [3., 0.],
       [5., 6.]])

In [151]:
np.concatenate([npa2d, npa2d], axis = 1)

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [5., 6., 5., 6.]])

In [152]:
np.concatenate([npa2d, arr], axis = 1) # u have to provide same size array

ValueError: all the input arrays must have same number of dimensions

In [153]:
np.vstack([npa2d, npa2d])

array([[0., 2.],
       [3., 0.],
       [5., 6.],
       [0., 2.],
       [3., 0.],
       [5., 6.]])

In [154]:
np.hstack([npa2d, npa2d])

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [5., 6., 5., 6.]])

In [155]:
npa = np.hstack([npa2d, npa2d])
npa

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [5., 6., 5., 6.]])

In [157]:
npa.sort()
npa

array([[0., 0., 2., 2.],
       [0., 0., 3., 3.],
       [5., 5., 6., 6.]])

## Working with Dates 

In [158]:
d = np.datetime64('2020-12-1 23:34:23')

ValueError: Error parsing datetime string "2020-12-1 23:34:23" at position 8

In [159]:
d = np.datetime64('2020-12-01 23:34:23')

In [160]:
d

numpy.datetime64('2020-12-01T23:34:23')

In [161]:
d+10  #10 is traet as second

numpy.datetime64('2020-12-01T23:34:33')

In [162]:
oneday = np.timedelta64(1,'D')

In [163]:
oneday

numpy.timedelta64(1,'D')

In [164]:
d+ oneday

numpy.datetime64('2020-12-02T23:34:23')

In [165]:
onemin = np.timedelta64(1, 'm')

In [166]:
onemin

numpy.timedelta64(1,'m')

In [167]:
d+onemin

numpy.datetime64('2020-12-01T23:35:23')

In [169]:
# for performing copy array
a = np.copy(arr)

In [170]:
a

array([ 3,  5, 67, 45,  4,  6,  4])